# Bacterial single-copy marker genes HMM file
smg_hmm: "https://raw.githubusercontent.com/metagentools/MetaCoAG/develop/metacoag_utils/auxiliary/marker.hmm"
smg_hmm_file: "marker.hmm"

# PHROGs mmseqs database
phrogs_mmseqs: "https://phrogs.lmge.uca.fr/downloads_from_website/phrogs_mmseqs_db.tar.gz"
phrogs_mmseqs_file: "phrogs_mmseqs_db.tar.gz"
phrogs_mmseqs_folder: "phrogs_mmseqs_db/"

# PROHGs annotations
phrog_annot: "https://phrogs.lmge.uca.fr/downloads_from_website/phrog_annot_v4.tsv"
phrog_annot_file: "phrog_annot_v4.tsv"